engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
  - "server/tests/**/*.js"
exclude_paths:
- node_modules/
- server/dummyData/
- UI/
- client/
- build/